module.exports = [
  {
    _id: "63aa7bd042b1e0d90e533f35",
    fullName: {
      fname: "BENEDICT EARLE GABRIEL",
      mname: "ROMERO",
      lname: "PAJARILLAGA",
    },
    address: {
      street: "#25 Purok 2",
      barangay: "Mabini Extension",
      city: "Cabanatuan City",
      province: "Nueva Ecija",
      region: "Region III (Central Luzon)",
    },
    dob: "2000-09-08",
    role: "admin",
    mobile: "9762728299",
    email: "benedictearle@gmail.com",
    alias: "Quinn Tracy",
    password: "password",
    isMale: true,
    rate: 312.5,
    bio: "Quitting is always an option.",
  },
  {
    _id: "63aa7bd042b1e0d90e533f36",
    fullName: {
      fname: "KIMBERLY",
      // mname: "PENAFLOR",
      lname: "SARMIENTO",
    },
    // address: {
    //   street: "#25 Purok 2",
    //   barangay: "Mabini Extension",
    //   city: "Cabanatuan City",
    //   province: "Nueva Ecija",
    //   region: "Region III (Central Luzon)",
    // },
    // dob: "1999-10-12",
    company: "641fc727bad6d359fc2833e2",
    role: "owner",
    email: "owner@gmail.com",
    mobile: "9510706841",
    // alias: "Quinn Lotus",
    password: "password",
    rate: 0,
  },
  {
    _id: "63aa7bd042b1e0d90e533f37",
    fullName: {
      fname: "TAN",
      // mname: "PENAFLOR",
      lname: "CAKTIONG",
    },
    // address: {
    //   street: "#25 Purok 2",
    //   barangay: "Mabini Extension",
    //   city: "Cabanatuan City",
    //   province: "Nueva Ecija",
    //   region: "Region III (Central Luzon)",
    // },
    // dob: "1999-10-12",
    company: "641fc727bad6d359fc2833e3",
    role: "owner",
    email: "jollibee@gmail.com",
    mobile: "9510706842",
    // alias: "Quinn Lotus",
    password: "password",
    rate: 0,
  },
  {
    _id: "63aa7bd042b1e0d90e533f38",
    fullName: {
      fname: "GEORGE",
      mname: "TAN",
      lname: "YANG",
    },
    // address: {
    //   street: "#25 Purok 2",
    //   barangay: "Mabini Extension",
    //   city: "Cabanatuan City",
    //   province: "Nueva Ecija",
    //   region: "Region III (Central Luzon)",
    // },
    // dob: "1999-10-12",
    company: "641fc727bad6d359fc2833e4",
    role: "owner",
    email: "mcdo@gmail.com",
    mobile: "9510706843",
    // alias: "Quinn Lotus",
    password: "password",
    rate: 0,
  },
  {
    _id: "63aa7bd042b1e0d90e533f39",
    fullName: {
      fname: "GAURAV",
      // mname: "TAN",
      lname: "SARIA",
    },
    // address: {
    //   street: "#25 Purok 2",
    //   barangay: "Mabini Extension",
    //   city: "Cabanatuan City",
    //   province: "Nueva Ecija",
    //   region: "Region III (Central Luzon)",
    // },
    // dob: "1999-10-12",
    company: "641fc727bad6d359fc2833e5",
    role: "owner",
    email: "infinitea@gmail.com",
    mobile: "9510706844",
    // alias: "Quinn Lotus",
    password: "password",
    rate: 0,
  },
  {
    _id: "63aa7bd042b1e0d90e533f40",
    fullName: {
      fname: "HENRY",
      // mname: "TAN",
      lname: "SY",
    },
    // address: {
    //   street: "#25 Purok 2",
    //   barangay: "Mabini Extension",
    //   city: "Cabanatuan City",
    //   province: "Nueva Ecija",
    //   region: "Region III (Central Luzon)",
    // },
    // dob: "1999-10-12",
    company: "641fc727bad6d359fc2833e6",
    role: "owner",
    email: "sm@gmail.com",
    mobile: "9510706845",
    // alias: "Quinn Lotus",
    password: "password",
    rate: 0,
  },
  {
    _id: "63aa7bd042b1e0d90e533f41",
    fullName: {
      fname: "ADI",
      // mname: "TAN",
      lname: "DASSLER",
    },
    // address: {
    //   street: "#25 Purok 2",
    //   barangay: "Mabini Extension",
    //   city: "Cabanatuan City",
    //   province: "Nueva Ecija",
    //   region: "Region III (Central Luzon)",
    // },
    // dob: "1999-10-12",
    company: "641fc727bad6d359fc2833e7",
    role: "owner",
    email: "adidas@gmail.com",
    mobile: "9510706846",
    // alias: "Quinn Lotus",
    password: "password",
    rate: 0,
  },
  {
    _id: "63aa7bd042b1e0d90e533f42",
    fullName: {
      fname: "LEVI",
      // mname: "TAN",
      lname: "STRAUSS",
    },
    // address: {
    //   street: "#25 Purok 2",
    //   barangay: "Mabini Extension",
    //   city: "Cabanatuan City",
    //   province: "Nueva Ecija",
    //   region: "Region III (Central Luzon)",
    // },
    // dob: "1999-10-12",
    company: "641fc727bad6d359fc2833e8",
    role: "owner",
    email: "levis@gmail.com",
    mobile: "9510706847",
    // alias: "Quinn Lotus",
    password: "password",
    rate: 0,
  },
  {
    _id: "63aa7bd042b1e0d90e533f43",
    fullName: {
      fname: "KATE",
      // mname: "TAN",
      lname: "WANG",
    },
    // address: {
    //   street: "#25 Purok 2",
    //   barangay: "Mabini Extension",
    //   city: "Cabanatuan City",
    //   province: "Nueva Ecija",
    //   region: "Region III (Central Luzon)",
    // },
    // dob: "1999-10-12",
    company: "641fc727bad6d359fc2833e9",
    role: "owner",
    email: "relx@gmail.com",
    mobile: "9510706848",
    // alias: "Quinn Lotus",
    password: "password",
    rate: 0,
  },
];
